---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env
spec:
  replicas: 3
  selector:
    matchLabels:
      hack: a75016fae105edb1bb462ac
  template:
    metadata:
      labels:
        hack: a75016fae105edb1bb462ac
    spec:
      containers:
        - image: filefrog/k8s-hacks:id
          imagePullPolicy: Always
          name: web
          ports:
            - name: web
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: env
spec:
  type: NodePort
  selector:
    hack: a75016fae105edb1bb462ac
  ports:
    - name: web
      port: 80
      targetPort: web
